CREATE OR REPLACE VIEW {object_name} AS
SELECT
    IFNULL("Unique Key", 'Unspecified') AS unique_key,
    IFNULL("Status", 'Unspecified') AS status,
    cast("Created Date" as timestamp) AS created_timestamp,
    cast(created_timestamp as date) AS created_date,
    date_trunc('week', created_timestamp) AS created_week,
    date_trunc('month', created_timestamp) AS created_month,
    date_trunc('year', created_timestamp) AS created_year,
    year(created_timestamp) AS created_year_datepart,
    month(created_timestamp) AS created_month_datepart,
    day(created_timestamp) AS created_day_datepart,
    hour(created_timestamp) AS created_hour_datepart,
    strftime('%a', created_timestamp) AS created_weekday_datepart,
    cast("Closed Date" as timestamp) AS closed_timestamp,
    cast(closed_timestamp as date) AS closed_date,
    year(closed_timestamp) AS closed_year_datepart,
    month(closed_timestamp) AS closed_month_datepart,
    day(closed_timestamp) AS closed_day_datepart,
    hour(closed_timestamp) AS closed_hour_datepart,
    strftime('%a', closed_timestamp) AS closed_weekday_datepart,
    datesub('second', created_timestamp, closed_timestamp) AS time_to_resolve_sec,
    IFNULL("Agency", 'Unspecified') AS agency,
    IFNULL("Agency Name", 'Unspecified') AS agency_name,
    CASE 
        WHEN "Complaint Type" IN (
            'HEATING',
            'PLUMBING',
            'ELECTRIC',
            'Water System',
            'Water Quality',
            'PAINT - PLASTER',
            'PAINT/PLASTER',
            'Window Guard',
            'Lead',
            'Asbestos',
            'Mold',
            'APPLIANCE',
            'NONCONST',
            'Building/Use',
            'Building Condition',
            'GENERAL CONSTRUCTION',
            'General Construction/Plumbing',
            'CONSTRUCTION',
            'Scaffold Safety',
            'Stalled Sites',
            'Boilers',
            'Interior Demo',
            'Best/Site Safety (B.E.S.T./Site Safety)',
            'Home Repair',
            'Weatherization',
            'HPD Literature Request',
            'Maintenance or Facility',
            'Non-Residential Heat'
        ) THEN 'Housing & Building Maintenance'
        WHEN "Complaint Type" IN (
            'Street Condition',
            'Sidewalk Condition',
            'Curb Condition',
            'Street Light Condition',
            'Street Sign - Damaged',
            'Street Sign - Missing',
            'Street Sign - Dangling',
            'Highway Condition',
            'Bridge Condition',
            'Tunnel Condition',
            'Highway Sign - Damaged',
            'Highway Sign - Missing',
            'Highway Sign - Dangling',
            'Snow',
            'Bus Stop Shelter Complaint',
            'Bus Stop Shelter Placement',
            'Public Payphone Complaint',
            'Municipal Parking Facility',
            'Bike Rack Condition'
        ) THEN 'Streets & Sidewalks'
        WHEN "Complaint Type" IN (
            'Traffic Signal Condition',
            'Broken Muni Meter',
            'Broken Parking Meter',
            'Parking Card',
            'Blocked Driveway',
            'Traffic',
            'Traffic/Illegal Parking',
            'Illegal Parking',
            'Derelict Vehicle',
            'Derelict Bicycle',
            'City Vehicle Placard Complaint',
            'Taxi Complaint',
            'Taxi Compliment',
            'For Hire Vehicle Complaint',
            'Ferry Complaint',
            'Ferry Inquiry',
            'Ferry Permit',
            'DOF Parking - Payment Issue',
            'DOF Parking - Request Status',
            'DOF Parking - Request Copy',
            'DOF Parking - DMV Clearance',
            'DOF Parking - Tax Exemption',
            'DOF Parking - Address Update'
        ) THEN 'Traffic & Parking'
        WHEN "Complaint Type" IN (
            'Noise - Residential',
            'Noise',
            'Noise - Commercial',
            'Noise - Street/Sidewalk',
            'Noise - Vehicle',
            'Noise - House of Worship',
            'Noise - Helicopter',
            'Noise - Park',
            'Noise Survey',
            'Collection Truck Noise',
            'Panhandling',
            'Disorderly Youth',
            'Urinating in Public',
            'Squeegee',
            'Illegal Fireworks',
            'Posting Advertisement',
            'Graffiti',
            'Drinking',
            'Non-Emergency Police Matter'
        ) THEN 'Noise & Quality of Life'
        WHEN "Complaint Type" IN (
            'Dirty Conditions',
            'Missed Collection (All Materials)',
            'Sanitation Condition',
            'Sweeping/Missed-Inadequate',
            'Overflowing Litter Baskets',
            'Litter Basket / Request',
            'Rodent',
            'Unsanitary Pigeon Condition',
            'Hazardous Materials',
            'Hazardous Material',
            'Industrial Waste',
            'Air Quality',
            'Indoor Air Quality',
            'Water Conservation',
            'Recycling Enforcement',
            'Poison Ivy',
            'Sewer'
        ) THEN 'Environmental & Sanitation'
        WHEN "Complaint Type" IN (
            'Damaged Tree',
            'Overgrown Tree/Branches',
            'New Tree Request',
            'Dead Tree',
            'Root/Sewer/Sidewalk Condition',
            'Violation of Park Rules',
            'Animal in a Park',
            'Beach/Pool/Sauna Complaint',
            'Lifeguard',
            'Summer Camp'
        ) THEN 'Greenery & Trees (Parks & Rec)'
        WHEN "Complaint Type" IN (
            'Food Establishment',
            'Food Poisoning',
            'Smoking',
            'Calorie Labeling',
            'Trans Fat',
            'Tattooing',
            'X-Ray Machine/Equipment',
            'Illegal Animal Kept as Pet',
            'Illegal Animal Sold',
            'Bottled Water'
        ) THEN 'Public Health & Food Safety'
        WHEN "Complaint Type" IN (
            'Homeless Encampment',
            'Elder Abuse',
            'Senior Center Complaint',
            'Alzheimer''s Care',
            'Home Care Provider Complaint',
            'SCRIE',
            'HEAP Assistance',
            'Housing Options',
            'Benefit Card Replacement',
            'Eviction',
            'Case Management Agency Complaint',
            'Legal Services Provider Complaint',
            'Home Delivered Meal Complaint',
            'Home Delivered Meal - Missed Delivery',
            'Transportation Provider Complaint',
            'DHS Advantage - Tenant',
            'DHS Advantage -Landlord/Broker',
            'DHS Advantage - Third Party',
            'DHS Income Savings Requirement'
        ) THEN 'Social Services & Community Support'
        WHEN "Complaint Type" IN (
            'Consumer Complaint',
            'DCA / DOH New License Application Request',
            'DOF Property - Owner Issue',
            'DOF Property - Reduction Issue',
            'DOF Property - Request Copy',
            'DOF Property - Payment Issue',
            'DOF Property - City Rebate',
            'DOF Property - RPIE Issue',
            'DOF Property - Property Value',
            'DOF Property - State Rebate',
            'Registration and Transfers',
            'Investigations and Discipline (IAD)',
            'Forensic Engineering',
            'Forms',
            'Vending'
        ) THEN 'Administrative, Regulatory & Financial'
        ELSE 'Other'
    END AS complaint_category,
    IFNULL("Complaint Type", 'Unspecified') AS complaint_type,
    IFNULL("Descriptor", 'Unspecified') AS complaint_descriptor,
    IFNULL("Street Name", 'Unspecified') AS street_name,
    REGEXP_EXTRACT(
        "Incident Address",
        CONCAT('([0-9\\-]+) ', "Street Name"),
        1
    ) AS street_number,
    IFNULL("Borough", 'Unspecified') AS borough,
    CASE
        WHEN IFNULL("Borough", 'Unspecified') = 'MANHATTAN' THEN 'NEW YORK'
        WHEN IFNULL("Borough", 'Unspecified') = 'BROOKLYN' THEN 'KINGS'
        WHEN IFNULL("Borough", 'Unspecified') = 'QUEENS' THEN 'QUEENS'
        WHEN IFNULL("Borough", 'Unspecified') = 'BRONX' THEN 'BRONX'
        WHEN IFNULL("Borough", 'Unspecified') = 'STATEN ISLAND' THEN 'RICHMOND'
        ELSE 'Unspecified'
    END AS county,
    IFNULL("Incident Zip", 'Unspecified') AS incident_zip,
    "Location" AS location,
    IFNULL(neighborhood_code, 'Unspecified') AS neighborhood_code,
    IFNULL(neighborhood_name, 'Unspecified') AS neighborhood_name
FROM
    read_parquet('{object_url}');